version: '3.10'
services:

  warehouse:
    container_name: warehouse_api
    restart: on-failure
    build: .
    expose:
      - '8000'
    env_file:
      - ./.env.dev
    depends_on:
      # rabbitmq:
        # condition: service_healthy      # пока не запуститься служба RabbitMQ не запускать сервис Warehouse
      warehouse_db:
        condition: service_healthy      # пока не запуститься База данных не запускать сервис Warehouse
    command: sh -c "python manage.py makemigrations api && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    python manage.py collectstatic --no-input && \
                    gunicorn warehouse.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      # для обмена данными между локальной директорией проекта и такой же директорией в контейнере (/path/on/host:/path/in/container)
      - static_volume:/usr/src/warehouse/static

  warehouse_db:
    container_name: warehouse_db
    image: mysql:8.0.33
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/usr/src/warehouse/mysql/
    environment:
      - MYSQL_DATABASE=warehouse_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
    expose:
      - '3306'
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - warehouse
    volumes:
      - static_volume:/usr/src/warehouse/static

volumes:
  mysql_data:
  static_volume: