version: '3.10'
services:

  warehouse:
    container_name: warehouse_api
    build: .
    expose:
      - '8000'
    env_file:
      - ./.env.dev
    depends_on:
      rabbitmq:
        condition: service_healthy
      warehouse_db:
        condition: service_healthy
    command: sh -c "python manage.py makemigrations api && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn warehouse.wsgi:application --bind 0.0.0.0:8000"

  warehouse_db:
    container_name: warehouse_db
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=warehouse_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
    expose:
      - '3306'
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12.0-management
    hostname: rabbitmq
    # restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=brewery
      - RABBITMQ_DEFAULT_PASS=brewery
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - warehouse