version: '3.10'
services:
  accounting:
    build:
      context: ./accounting
      dockerfile: Dockerfile
    expose:
      - '8000'
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - MYSQL_HOST=accounting_db
      - MYSQL_PORT=3306
      - MYSQL_DB=accounting_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
    depends_on:
      - accounting_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn --bind 0.0.0.0:8001 project.wsgi:application"

  sales:
    build:
      context: ./sales
      dockerfile: Dockerfile
    expose:
      - '8001'
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - MYSQL_HOST=sales_db
      - MYSQL_PORT=3306
      - MYSQL_DB=sales_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
    depends_on:
      - sales_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn --bind 0.0.0.0:8000 project.wsgi:application"

  warehouse:
    build:
      context: ./warehouse
      dockerfile: Dockerfile
    expose:
      - '8002'
    env_file:
      - ./warehouse/.env.dev
    depends_on:
      - warehouse_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn --bind 0.0.0.0:8002 project.wsgi:application"

  accounting_db:
    image: mysql:5.7
    volumes:
      - ./accounting/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=accounting_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - '3306:3306'

  sales_db:
    image: mysql:5.7
    volumes:
      - ./sales/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sales_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - '3306:3306'

  warehouse_db:
    image: mysql:5.7
    volumes:
      - ./warehouse/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=warehouse_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=brewery
      - RABBITMQ_DEFAULT_PASS=brewery
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - accounting
      - sales
      - warehouse
