version: '3.10'
services:

  rabbitmq:
    image: rabbitmq:3.12.0-management
    hostname: rabbitmq
    # restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=brewery
      - RABBITMQ_DEFAULT_PASS=brewery
    expose:
      - 5672
      - 15672

  accounting:
    build:
      context: ./accounting
      dockerfile: Dockerfile
    expose:
      - '8000'
    env_file:
      - ./accounting/.env.dev
    depends_on:
      - accounting_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn --bind 0.0.0.0:8000 accounting.wsgi:application"

  sales:
    build:
      context: ./sales
      dockerfile: Dockerfile
    expose:
      - '8001'
    env_file:
      - ./sales/.env.dev
    depends_on:
      - sales_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations api && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    gunicorn --bind 0.0.0.0:8001 sales.wsgi:application"

  warehouse:
    build:
      context: ./warehouse
      dockerfile: Dockerfile
    expose:
      - '8002'
    env_file:
      - ./warehouse/.env.dev
    depends_on:
      - warehouse_db
      - rabbitmq
    command: sh -c "python manage.py makemigrations api && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --email with --noinput && \
                    gunicorn --bind 0.0.0.0:8002 warehouse.wsgi:application"

  accounting_db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./accounting/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=accounting_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    expose:
      - '3306'

  sales_db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sales/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sales_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    expose:
      - '3306'

  warehouse_db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./warehouse/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=warehouse_db
      - MYSQL_USER=brewery
      - MYSQL_PASSWORD=brewery
      - MYSQL_ROOT_PASSWORD=brewery
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    expose:
      - '3306'

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - accounting
      - sales
      - warehouse
